### ISSUE TITLE
Feedback on kr8s

### ISSUE THREAD

**Issue by stanislavhordiyenko** [kr8s-org/kr8s#232]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

Hi, I would like to write a quick feedback on kr8s. The library is easy to use and very intuitive, code is easy to write and maintain. In the past, I tried kopf and native kubernetes library to write simple scripts and found quite difficult them to use, not much examples in the Internet and it took a while to write bit by bit, so I decided to use kubectl instead and bash script that was not easy either but at least there are plenty of examples on it.

I would like to write several small scripts using kr8s library. First of all, I found that we have so many abandoned resources in the cluster (no, we cannot just simply destroy it), certificates that were generated by cert-manager, deployments that were removed, but helm artifacts were left, many configmaps and secrets and so on. I would like to write a script that will do an audit in the cluster and remove all resources that are no longer in use.

Next, I would like to create a controller that will rescale workloads base on schedule + reshufling pods on the node (in dev, we have feature branch deployments and some nodes still exists as one pod was scheduled there and holds it from removal).

Once again, thanks a lot for an awesome piece of art.

**Comment by stanislavhordiyenko** [comment]
One more use case, I need to patch memory and cpu resources for the deployment. Unfortunately, I was not able to do so with `kubectl patch` command, so with the library it is straight forward as well.

**Comment by jacobtomlinson** [comment]
Awesome thank you so much for taking the time to let me know what you're doing with `kr8s`. Your auditing scripts sound like a great use case for `kr8s`.

You could also definitely write controllers with `kr8s`. I maintain another project called `dask-kubernetes` which has a controller that is written with `kopf` and `kr8s`. I really like using the event triggers from `kopf` but prefer to use `kr8s` to make changes to the cluster. I should totally write up some examples of doing this because the two projects work really well together!

Thanks again!
