### ISSUE TITLE
Need to add ec2nodeclass object to kr8s

### ISSUE THREAD

**Issue by nareshb123a** [kr8s-org/kr8s#391]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

Need to add karpenter ec2nodeclass object 

```python
class EC2NodeClass(APIObject):
    """Karpenter custom resource."""

    version = "karpenter.k8s.aws/v1beta1"
    endpoint = "ec2nodeclasses"
    kind = "EC2NodeClass"
    plural = "ec2nodeclasses"
    singular = "ec2nodeclass"
    namespaced = False
```

Its plural name has 'es' instead of 's', new_class object doesn't work. Please add this to use kr8s in our environments

**Comment by jacobtomlinson** [comment]
There should be no issue with creating the subclass directly as you have in the example you gave, the `new_class()` function is just to add a little convenience. However if you want to use the sync API instead of the asyncio one you'll need to import the private sync wrapper.


```python
from kr8s._objects import APIObject
from kr8s._async_utils import sync

@sync
class EC2NodeClass(APIObject):
    """Karpenter custom resource."""
    version = "karpenter.k8s.aws/v1beta1"
    endpoint = "ec2nodeclasses"
    kind = "EC2NodeClass"
    plural = "ec2nodeclasses"
    singular = "ec2nodeclass"
    namespaced = False
```

I've also opened #392 to allow you to do this with `new_class()` and avoid using private methods.
```python
from kr8s.objects import new_class

EC2NodeClass = new_class(
    kind="EC2NodeClass",
    version="karpenter.k8s.aws/v1beta1",
    namespaced=False,
    plural_suffix="es",
    asyncio=False,
)
```
